
spring:
  datasource: # H2 DB ??
    url: jdbc:h2:mem:JPATest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true # H2 DB ??? ????? ?? (http://localhost:8080/h2-console)
  jpa:
    open-in-view: false
    database: H2
    show-sql: true # jpa ?? ? SQL? ?? ??
    properties:
      hibernate:
        format_sql: true # ?? ??? ?? ????? ??

oauth2:
  google:
    client-id:
    client-secret:
    redirect-uri:
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo